FROM java:8
#VOLUME /tmp
ADD  EurekaServer-0.0.1-SNAPSHOT.jar /home/ubuntu/puppet_shoppingcarteureka/
CMD ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/home/ubuntu/puppet_shoppingcarteureka/EurekaServer-0.0.1-SNAPSHOT.jar"]

