FROM java:8
#VOLUME /tmp
ADD ShoppingCart-0.0.1-SNAPSHOT.jar /home/ubuntu/puppet_shoppingcart/
CMD ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/home/ubuntu/puppet_shoppingcart/ShoppingCart-0.0.1-SNAPSHOT.jar"]

